with-expecter: True
packages:
  github.com/ansh-devs/commercelens/product-service/repo:
    interfaces:
      Repository:
        config:
          with-expecter: True
        configs:
          - mockname: MockRequesterVariadicOneArgument
            unroll-variadic: False
          - mockname: MockRequesterVariadic